version: "3"
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./app:/var/www/app
      - ./container-config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
  
  php:
    image: brian978/php-fpm:7.2
    volumes:
      - ./app:/var/www/app
      - ./container-config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php
      - ./profile/php/bash_profile:/root/.bash_profile
      - ./bin/php/:/usr/local/bin/external

  mysql:
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  memcache:
    image: memcached:1.5

volumes:
  mysql-volume:
  mssql-volume:
