version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
      - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
  
  php:
    image: brian978/php-fpm:7.4
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
      - ./services/fpm/www.conf.dist:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php

  mysql:
    image: mariadb:latest
    ports:
      - "33061:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker-stack
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 12345

  memcache:
    image: memcached:latest

volumes:
  mysql-volume:
