version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./app:/var/www/app
      - ./container-config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
  
  php:
    image: nanoninja/php-fpm:latest
    links:
      - db
    volumes:
      - ./app:/var/www/app
      - ./container-config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php

  db:
    image: mysql:latest
    ports:
      - "33061:3306"
    volumes:
      - ./persistent/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345